spring:
  datasource:
    url: jdbc:mysql://live.db.server.org:3306/travellers
    password: SomePassword
    username: root
    hikari:
      maximum-pool-size: 64
      data-source-properties:
        cachePrepsStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultsSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  flyway:
    schemas: travellers
    out-of-order: false
    locations: "classpath:/db/scripts"
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:13308/travellers?createDatabaseIfNotExist=true
    password: LetMeIn2023
    username: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: service
      password: s$rv1c$2ol3!
server:
  port: 8081
